### PR TITLE
Homescreen

### PR DESCRIPTION
**Pull request by girumel**
The UI design for the homescreen is almost done.
The placeholder avatars can be replaced by the actual drawable resources.

### CODE REVIEW

**Comment by otoo-peacemaker** [comment]
Alright.

**Review by otoo-peacemaker — CHANGES_REQUESTED** [review]
Please let the design matches the UI.
I have added font to the project in my branch in case you need it.

**Comment by girumtimerga** [comment]
What about the image resources? Where can I find them?

**Comment by otoo-peacemaker** [comment]
Like i said everything is available there and you just need to export it.
Schedule a meeting tomorrow and lemme teach you how to do that.

**Pull request closed without merging**
